### ISSUE TITLE
Legal or Not?

### ISSUE THREAD

**Issue by alexdanca** [CZ4B/RDP#10]
I like your work, I want to know if I violate the terms and conditions if I use this, have I noticed that many people tell me that I violate the terms if I use this? From what I understand (action) is unlimited on the public and I did not find that I would violate terms what do you say?
I program often and a lot of unlimited 6h helps me to program and I save my data in github

**Comment by C4B1CA90E0B98F** [comment]
the main purpose of github actions is used to test your coded application running smoothly or not when you want to upload it to github while this project is made to test in more detail not run it continuously. maybe if you use for other it's illegal thing like you do...

**Comment by alexdanca** [comment]
this method has been around for more than 2 years, but I use it every day for 6 hours and I didn't do it, I only made an appointment, I didn't receive a warning or problems like that.

**Comment by alexdanca** [comment]
I remember Microsoft Github responding to that and saying it had nothing to do with it

**Comment by C4B1CA90E0B98F** [comment]
so?

**Comment by alexdanca** [comment]
said something like "each account shares different experiences"
