### ISSUE TITLE
Ubuntu 

### ISSUE THREAD

**Issue by alexdanca** [CZ4B/RDP#11]
Password? No work install pakage ? And password user Ubuntu?

**Comment by alexdanca** [comment]
sudo su?
And
passwd
And 
passwd runner
And 
passwd runner admin?

**Comment by C4B1CA90E0B98F** [comment]
if you want to install just start with the command `sudo`. with sudo you will not be asked for a password

**Comment by alexdanca** [comment]
Sudo su and finish ok.
